learning_rate: 0.0001
weight_decay: 0.000005
epochs: 200
batch_size: 2
pfd_weight: 1.0
roi_weight: 0.5
sequence_length: 5
attention_feat_output_size: 64
pointcloud_feat_output_size: 256
pointcloud_source: "synthetic_dense" #[ "synthetic_dense", "synthetic_sparse", "kinect" ]
objects: [ "Dice" ]
data_path: "data/processed"
output_path: "data/training"
