learning_rate: 0.0001
weight_decay: 0.000005
epochs: 200
batch_size: 4
pfd_weight: 1.0
roi_weight: 0.5
sequence_length: 5
attention_feat_output_size: 64
image_feat_output_size: 128
force_feat_output_size: 32
cameras: ["volucam0"]
objects: [ "Dice" ]
data_path: "data/processed"
output_path: "data/training"

